name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t crypto101 docker/
      - name: Generate documents
        shell: 'script -q -e -c "bash {0}"'
        run: |
          set -x
          set -e
          docker run --rm -it -v ${{ github.workspace }}:/repo crypto101 ./build_release ./_release/
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-en.epub
          path: _release/crypto101-en.epub
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-en.pdf
          path: _release/crypto101-en.pdf
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-en_html.tar.gz
          path: _release/crypto101-en_html.tar.gz
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-fr.epub
          path: _release/crypto101-fr.epub
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-fr.pdf
          path: _release/crypto101-fr.pdf
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: crypto101-fr_html.tar.gz
          path: _release/crypto101-fr_html.tar.gz
